apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  namespace: argocd
spec:
  tolerations:
    - key: eks.amazonaws.com/compute-type
      operator: Equal
      value: fargate
  dnsPolicy: ClusterFirst
  containers:
    - name: netshoot
      image: nicolaka/netshoot:latest
      command: ["/bin/sh", "-c", "sleep infinity"]
