apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: kube-prometheus-stack-grafana
  namespace: kube-prometheus-stack
spec:
  refreshInterval: 240h
  secretStoreRef:
    name: cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: kube-prometheus-stack-grafana
    creationPolicy: Owner
  data:
  - secretKey: admin-user
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: ci_cluster_grafana_secret
      property: admin-user
  - secretKey: admin-password
    remoteRef:
      key: ci_cluster_grafana_secret
      property: admin-password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
