apiVersion: v2
name: karpenter
description: Helm chart providing karpenter
type: application
version: 0.1.0
appVersion: 1.0
dependencies:
- name: karpenter
  version: 0.16.3
  repository: https://charts.karpenter.sh
