name: Terraform Deploy

on:
  push:
    branches:
    - main
    paths:
    - 'terraform/**'
    - .github/workflows/terraform.yaml


permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  plan-and-approve:
    runs-on: ubuntu-latest
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3.0.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ secrets.AWS_REGION }}
    - name: install terraform
      uses: hashicorp/setup-terraform@v2
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Arrange environment files
      run: |
        cp terraform/environments/prod/terraform.tfvars terraform/
        cp terraform/environments/prod/provider.tf terraform/
    - name: terraform init
      run: terraform init
      working-directory: terraform
    - name: terraform plan
      run: terraform plan
      working-directory: terraform

  
  execute-plan:
    runs-on: ubuntu-latest
    needs: plan-and-approve
    environment: production # This is required for the approval step
    steps:
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v3.0.1
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHub_to_AWS_via_FederatedOIDC
        aws-region: ${{ secrets.AWS_REGION }}
    - name: install terraform
      uses: hashicorp/setup-terraform@v2
    - name: checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'true'
    - name: Arrange environment files
      run: |
        cp terraform/environments/prod/terraform.tfvars terraform/
        cp terraform/environments/prod/provider.tf terraform/
    - name: terraform init
      run: terraform init
      working-directory: terraform/environments/prod
    - name: terraform apply
      run: terraform apply -auto-approve
      working-directory: terraform/environments/prod