name: "Terraform Apply"

on:
  pull_request:
    types: [closed]
    branches:
      - main
    paths:
      - "terraform/**"
      - .github/workflows/terraform-apply.yaml

  workflow_dispatch:

permissions: write-all

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3.0.1
        with:
          # role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          # role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: verify aws  profile
        run: |
          aws sts get-caller-identity
          aws configure list
      - name: install terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.13.3"
      - name: checkout repository
        uses: actions/checkout@v5
        with:
          submodules: "true"
      - name: terraform init
        run: terraform init
        working-directory: terraform/environments/prod
      - name: terraform apply
        run: terraform apply -auto-approve
        working-directory: terraform/environments/prod
