name: Terraform Destroy

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions: write-all

jobs:
  destroy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5.0.0
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: install terraform
        uses: hashicorp/setup-terraform@v2

      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: "true"

      - name: configure kubectl
        continue-on-error: true
        run: |
          aws eks update-kubeconfig --name ${{ vars.EKS_CLUSTER_NAME }} --region ${{ vars.AWS_REGION }}

      - name: checkout code
        uses: actions/checkout@v5

      - name: delete resources created not managed by terraform
        continue-on-error: true
        run: |
          kubectl delete -f kubernetes/ingress # deletes ALB created by aws-load-balancer-controller
          kubectl delete nodeclaims --all # deletes nodes created by karpenter
          sleep 120

      - name: terraform init
        run: terraform init
        working-directory: terraform

      - name: terraform destroy
        run: terraform destroy -auto-approve -lock=false
        working-directory: terraform
